### ISSUE TITLE
cocoapods support?

### ISSUE THREAD

**Issue by jafara** [scribd/LiveCollections#1]
i use cocoapods for development and would like to use this library in my project. Can you please upload a podspec?

**Comment by StephaneMagne** [comment]
Hi, thanks for your interest!

I'll be adding CocoaPods support shortly and I'll send you a message as
soon as it's published.

Cheers,
Stephane

**Comment by StephaneMagne** [comment]
CocoaPods is now supported!

Add either line to your Podfile:

pod 'LiveCollections', '~> 0.9.6'
pod 'LiveCollections'

Cheers,
Stephane

**Comment by StephaneMagne** [comment]
CocoaPods officially supported as of version 0.9.6
