### ISSUE TITLE
Does diffable render this code obsolete? could it be updated to support diffable?

### ISSUE THREAD

**Issue by 8secz-johndpope** [scribd/LiveCollections#3]

**Comment by StephaneMagne** [comment]
Hi John, thanks for your interest and feedback.

I think that Diffable fills a similar space but in the SwiftUI world.  Anyone planning to develop entirely in SwiftUI would probably be best served by adopting the DiffableDataSources that Apple provides, right away.

LiveCollections is wholly designed to support apps that are using (and plan to continue using) UIKit and the standard interfaces for UITableView and UICollectionView.

Additionally, one area I feel that LiveCollections offers a more powerful interface than Diffable is in its simplicity of interface. Once your data classes have adopted the required protocols, you simply need to call `collectionData.update(newData)`, whereas Diffable still (as of this comment) requires to supply additional details with every update.

**Comment by 8secz-johndpope** [comment]
Fyi - the reload of data when animating differences is known by Apple to be hard to get right. Frequent cause of crashes.
I'm on a quest to remove any code that references reloadData due to this. 
https://developer.apple.com/videos/play/wwdc2019/220

 I haven't touched SwiftUI - probably give it a whirl when ios15 hits.
